version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "
      python3 manage.py migrate &&
      python3 manage.py loaddata data.json &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A learnify worker --loglevel=info
    depends_on:
      - redis
      - django
    volumes:
      - ./:/app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A learnify beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - django
    volumes:
      - ./:/app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: