services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  postgres:
      image: postgres:16.3-alpine
      container_name: postgres
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      expose:
        - "5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "
      python3 manage.py migrate &&
      python3 manage.py loaddata data.json &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  celery:
    build: .
    tty: true
    command: celery -A learnify worker --loglevel=info
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      - redis
      - django
      - postgres

  celery-beat:
    build: .
    tty: true
    command: celery -A learnify beat --loglevel=info
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      - redis
      - django
      - postgres

volumes:
  postgres_data:
